### ISSUE TITLE
--fix option not working

### ISSUE THREAD

**Issue by dustinhorton** [gmsorrow/eslint-plugin-modules-newline#1]
Stoked you're trying to tackle this. Just installed and it seems to be linting just fine (I'm getting expected lint feedback errors), but `--fix` doesn't seem to modify despite the issues seeming fix-able:

```console
✖ 63 problems (63 errors, 0 warnings)
  63 errors and 0 warnings potentially fixable with the `--fix` option.
```

Let me know if I can help debug.

**Comment by gmsorrow** [comment]
Hello, @dustinhorton .
That's weird, it works for me.
Could you please provide an example?

**Comment by dustinhorton** [comment]
@gmsorrow did some debugging it looks like it was actually a prettier conflict unfortunately.
